### ISSUE TITLE
Chart doesn't appear, or appears with inconsistent opacity

### ISSUE THREAD

**Issue by CharlieHess** [codecapers/c3-chart-maker#1]
I've been stuck on this for hours and tried all kinds of silly things, so figured I'd file an issue (and then close it, because I finally figured it out).

The issue, as it turns out, is caused by the chart "fading in." The timeout on Nightmare is only based on the svg existing, not the animation end, so depending on timing you can get a chart that's empty, or varying levels of faded in. The trick is to add

``` json
"transition": {
  "duration": 0
}
```

To your chart schema. This is shown in the examples but not called out as important. Friends: it truly is.

**Comment by ashleydavis** [comment]
Oh yeah, it's a pain figuring this out.

Anyway I don't maintain or use this code any more. I'm going to put a warning at the top of the readme.

These day I recommend [Data-Forge Plot](https://www.npmjs.com/package/data-forge-plot) for server side rendering of charts.
